### PR TITLE
Small bug fixes

### PR DESCRIPTION
**Pull request by Scavengrove**
Fixes the crashes resulting from the mouse transparency function rename.

Updates all active meter windows when opacity settings are changed.

### CODE REVIEW

**Comment by Narthorn** [comment]
Hey. Thanks for the PR !

I looked into it, and the crash was actually not introduced by the rename, but by the commit right before, cd0eec44c647511662a022af0296dfc3871a3846. Before that one, "window" was defined as a global variable in Window:init(), and used as such in the transparency setting config window. This is pretty bad by itself, and it breaks down anyway for multiple windows.

To rename RM.settings.windowtransparancy, we'd also have to modify OnRestore so that it copies the value stored for the old name to the new one, so that the setting isn't lost when a user upgrades from 1.3.5 to the next version.

I'll fix the above issues and merge this in a short while.

**Comment by Scavengrove** [comment]
Right on. Thanks for the polite response despite me clearly not knowing LUA, haha. Keep up the good work mister, it is widely appreciated!

**Comment by Narthorn** [comment]
No problem, I would honestly have missed this since I don't usually use transparency options myself.
I squashed and edited your commits for clarity, but here they are : https://github.com/Narthorn/VortexMeter/commits/2e5a2a036809a2b34694e26ceb4b1d32f89a3efd

**Comment by Scavengrove** [comment]
Awesome! Thanks very much :)

**Pull request closed without merging**
